# Generated by Django 4.2.6 on 2023-12-03 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id_agenda', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.DateTimeField()),
                ('hora', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id_doctor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_doctor', models.CharField(max_length=150)),
                ('titulo', models.CharField(max_length=150)),
                ('correo', models.CharField(max_length=150)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='doctores/')),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_especialidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_especialidad', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_medicamento', models.CharField(max_length=100)),
                ('gramos', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('rut_paciente', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nombre_paciente', models.CharField(max_length=150)),
                ('direccion_paciente', models.CharField(max_length=200)),
                ('telefono_paciente', models.CharField(max_length=20)),
                ('correo_paciente', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_permiso', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipousuario',
            fields=[
                ('id_tipousuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipousuario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id_receta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('sexo', models.CharField(max_length=20)),
                ('edad', models.CharField(max_length=20)),
                ('instrucciones', models.CharField(max_length=500)),
                ('doctor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.doctor')),
                ('medicamentos', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.medicamentos')),
                ('rutPaciente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipousuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.tipousuario'),
        ),
        migrations.CreateModel(
            name='FichaPaciente',
            fields=[
                ('id_ficha', models.AutoField(primary_key=True, serialize=False)),
                ('anamnesis', models.CharField(max_length=100)),
                ('diagnostico', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('doctor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.doctor')),
                ('paciente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.paciente')),
                ('receta', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.receta')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='especialidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.especialidad'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='tipousuario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.tipousuario'),
        ),
    ]
