# Generated by Django 4.2.6 on 2023-12-01 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_agenda', models.IntegerField()),
                ('dia', models.DateTimeField()),
                ('hora', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_especialidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_especialidad', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FichaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ficha', models.IntegerField()),
                ('anamnesis', models.CharField(max_length=100)),
                ('diagnostico', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('rut_paciente', models.CharField(max_length=100)),
                ('id_doctor', models.IntegerField(default=0)),
                ('id_especialidad', models.IntegerField(default=0)),
                ('id_receta', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_medicamento', models.IntegerField()),
                ('nombre_medicamento', models.CharField(max_length=100)),
                ('gramos', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_paciente', models.CharField(max_length=13)),
                ('nombre_paciente', models.CharField(max_length=150)),
                ('direccion_paciente', models.CharField(max_length=200)),
                ('telefono_paciente', models.CharField(max_length=20)),
                ('correo_paciente', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_permiso', models.IntegerField()),
                ('nombre_permiso', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_receta', models.IntegerField()),
                ('medicamentos', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('rutPaciente', models.CharField(max_length=10)),
                ('id_doctor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipousuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tipousuario', models.IntegerField()),
                ('nombre_tipousuario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id_doctor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_doctor', models.CharField(max_length=150)),
                ('titulo', models.CharField(max_length=150)),
                ('correo', models.CharField(max_length=150)),
                ('id_agenda', models.IntegerField(default=0)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='doctores/')),
                ('especialidad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.especialidad')),
            ],
        ),
    ]
