# Generated by Django 4.2.6 on 2023-12-02 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichapaciente',
            name='especialidad',
        ),
    ]
