# Generated by Django 4.2.7 on 2023-12-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_doctor', models.IntegerField()),
                ('nombre_doctor', models.CharField(max_length=150)),
                ('titulo', models.CharField(max_length=150)),
                ('id_especialidad', models.IntegerField()),
                ('correo', models.CharField(max_length=150)),
                ('id_agenda', models.IntegerField(default=0)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='doctores/')),
            ],
        ),
        migrations.DeleteModel(
            name='Medico',
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='id_medicamento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rut_paciente',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='receta',
            name='rutPaciente',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tipousuario',
            name='nombre_tipousuario',
            field=models.CharField(max_length=100),
        ),
    ]
