# Generated by Django 4.2.6 on 2023-11-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_paciente', models.CharField(max_length=9)),
                ('nombre_paciente', models.CharField(max_length=150)),
                ('direccion_paceinte', models.CharField(max_length=200)),
                ('telefono_paciente', models.CharField(max_length=20)),
                ('correo_paciente', models.CharField(max_length=150)),
            ],
        ),
        # migrations.DeleteModel(
        #     name='Project',
        # ),
    ]
