# Generated by Django 4.2.7 on 2023-12-01 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0002_doctor_delete_medico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='id_especialidad',
        ),
        migrations.AddField(
            model_name='doctor',
            name='especialidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.especialidad'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id_doctor',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
