# Generated by Django 4.2.6 on 2023-12-03 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0002_remove_fichapaciente_especialidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='agenda',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='tipousuario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.tipousuario'),
        ),
    ]
